


spring.datasource.url=jdbc:sqlite:${user.home}/AppData/Local/Planify/planify.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# SQLite : une seule connexion en écriture à la fois
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

# Activer le mode WAL pour meilleures performances et éviter "database is locked"
spring.datasource.hikari.connection-init-sql=PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update


# ====================== Local JWT Configuration ======================
jwt.secret=bXktc3VwZXItc2VjcmV0LWtleS1mb3ItcGxhbmlmeS1hcHAteWFzcy1zdWlpMTIzNDU2Nzg5MA==
jwt.expiration=86400000
# =====================================================================


server.port=8080

# Logging de sécurité
logging.level.org.springframework.security=DEBUG

# Logging général
logging.level.root=INFO
logging.level.com.Session.EmploiTempsV1=DEBUG

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
